- name: variables
  hosts: localhost
  tasks:
  vars: # varibales declaration
    Course: "DevOps"
    institute: "joindevops"
    trainer: "sivakumar"
  - name: variables
    ansible.builtin.debug:
      msg: "Hi I am learning Ansible from joindevops trainer sivkumar"