- name: variables
  hosts: localhost
  vars:
    Course: "DevOps"
    institute: "joindevops"
    trainer: "sivakumar"
  tasks:
  - name: varibales
    ansible.builtin.debug:
      msg: "Hi I am learning {{Course}} from {{institute}} trainer {{trainer}}"