- name: variables
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: variables
    ansible.builtin.debug:
      msg: "Hi I am learning {{Course}} from {{institute}} trainer {{trainer}}"