- name: variables
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter username
    private: false
  - name: PASSWORD
    prompt: please enter password
    private: true
  tasks:
  - name: variables
    ansible.builtin.debug:
      msg: "Hi, Username : {{USERNAME}} and Password is : {{PASSWORD}}"