- name: variables
  hosts: localhost
  vars:
    WISHES: "Good morning from Play"
  #vars_files:
  #- vars.yaml
  #vars_prompt:
  #- name: WISHES
  #  prompt: Please enter wishes
  #  private: false
  tasks:
  - name: print information
    #vars:
    #  WISHES: "Good morning from Task"
    ansible.builtin.debug:
      msg: "Hi {{WISHES}}"

# 1. arguments
# 2. Task level
# 3. variable files
# 4. Prompt
# 5. Play level
# 6. inventory
# 7. role level