- name: Conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check user exist
    ansible.builtin.command: id expense
    register: USER
    ignore_error: true
  - name: display msg
    ansible.builtin.debug:
      msg: "Hello"