- name: conditions
  hosts: localhost
  become: true
  tasks:
  - name: check user exit or not
    ansible.builtin.command: id expense
  
  - name: print message
    ansible.builtin.debug:
      msg: "Hello"