- name: Conditions
  hosts: localhost
  vars_prompt:
  - name: number 
    prompt: please enter the number
    private: false
  tasks:
  - name: given number is greater than or not
    ansible.builtin.debug:
      msg: "Given number is {{number}} greater than 10"