- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - {'name': 'mysql', 'state': 'absent'}
    - {'name': 'git', 'state': 'latest'}
    - {'name': 'postfix', 'state': 'absent'}